# Generated by Django 3.1.5 on 2021-02-09 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('company_name', models.CharField(blank=True, max_length=50, verbose_name='company name')),
                ('industry_type', models.CharField(choices=[('AD', 'Advertising'), ('AG', 'Agriculture'), ('CN', 'Construction'), ('CM', 'Communications'), ('ED', 'Education'), ('EN', 'Entertainment'), ('FA', 'Fasion'), ('FI', 'Finance'), ('IT', 'Information Technology'), ('MA', 'Manufacturing'), ('RE', 'Retail'), ('TE', 'Technology'), ('TR', 'Transportation'), ('OT', 'Other Transportation Type')], default='OT', max_length=2, verbose_name='industry type')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='position')),
                ('website', models.CharField(blank=True, max_length=50, verbose_name='website')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('province_state', models.CharField(blank=True, max_length=20, verbose_name='province')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='country')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_reviewer', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),               
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'RLCIS Users',
            },
        ),
    ]
