# Generated by Django 3.1.4 on 2021-01-07 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('FullName', models.CharField(max_length=60, null=True)),
                ('PhoneNumber', models.CharField(default='XX-XXX-XXX-XXXX', max_length=15)),
                ('Address', models.CharField(default='DEFAULT ADDR', max_length=30)),
                ('City', models.CharField(default='DEFAULT CITY', max_length=20)),
                ('StateProvince', models.CharField(default='DEFAULT', max_length=12)),
                ('CompanyPosition', models.CharField(max_length=30)),
                ('Website', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
