# Generated by Django 3.1.5 on 2021-02-12 01:58

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=25, verbose_name='phone number'),
        ),
    ]
