# Generated by Django 2.2.7 on 2019-12-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='bribe_type',
            field=models.CharField(choices=[('CA', 'Cash'), ('FA', 'Favors'), ('GR', 'Gratuity'), ('GI', 'Gifts'), ('OT', 'Other Bribe Type')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='incident',
            name='bribed_by',
            field=models.CharField(choices=[('AG', 'Agent'), ('TP', 'Third Party'), ('PO', 'Public Official'), ('OT', 'Bribed by Other')], default='OT', max_length=2),
        ),
    ]
