# Generated by Django 3.1.4 on 2021-03-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='bribe_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcis.bribetype'),
        ),
        migrations.AddField(
            model_name='incident',
            name='bribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcis.bribedby'),
        ),
        migrations.AddField(
            model_name='incident',
            name='industry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcis.industrytype'),
        ),
        migrations.AddField(
            model_name='incident',
            name='levelOfAuthority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcis.levelofauthority'),
        ),
    ]
