# Generated by Django 2.2.7 on 2019-12-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0002_auto_20191201_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_details',
            field=models.TextField(default='not filed in', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_summary',
            field=models.CharField(default='not filed in', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='bribe_type_other',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='incident',
            name='bribed_by_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
