# Generated by Django 3.1.7 on 2021-03-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0002_auto_20210326_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='bribe_facilitator_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='bribe_initiator_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='bribe_recipient_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='bribe_type_other',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='industry_type_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
