# Generated by Django 3.1.7 on 2021-03-31 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rlcis', '0003_auto_20210326_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Has this been reviewed?', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
