# Generated by Django 3.1.4 on 2021-03-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0003_auto_20210303_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.FileField(upload_to='incidents/uploads/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/images/'),
        ),
    ]
