# Generated by Django 2.2.7 on 2019-12-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0004_auto_20191204_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rlcis.Reviewer'),
        ),
    ]
