# Generated by Django 3.1.4 on 2021-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0004_auto_20210303_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdocument',
            name='document',
            field=models.FileField(upload_to='rlcis/media/incidents/uploads/'),
        ),
    ]
