# Generated by Django 3.1.7 on 2021-04-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0005_auto_20210402_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Would you like to keep your Company Name, Region and Location, and Public Email address private?', null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='email',
            field=models.EmailField(default='public@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
