# Generated by Django 2.2.7 on 2019-12-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0005_auto_20191206_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
