# Generated by Django 3.1.4 on 2021-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0005_auto_20210303_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentdocument',
            name='document',
            field=models.FileField(upload_to='incidents/uploads/'),
        ),
    ]
