# Generated by Django 2.2.7 on 2019-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0006_auto_20191206_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='first_occurence',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolution_date',
            field=models.DateField(),
        ),
    ]
