# Generated by Django 3.1.7 on 2021-04-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0007_auto_20210406_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='submitted_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
