# Generated by Django 2.2.7 on 2019-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0007_auto_20191206_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='first_occurence',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolution_date',
            field=models.DateField(null=True),
        ),
    ]
