# Generated by Django 2.2.7 on 2019-12-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0009_auto_20191206_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rlcis.Reviewer'),
        ),
    ]
