# Generated by Django 2.2.7 on 2019-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0010_auto_20191206_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Would you like to submit this incident Anonymously?', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='industry_type',
            field=models.CharField(choices=[('AD', 'Advertising'), ('AG', 'Agriculture'), ('CN', 'Construction'), ('CM', 'Communications'), ('ED', 'Education'), ('EN', 'Entertainment'), ('FA', 'Fasion'), ('FI', 'Finance'), ('IT', 'Information Technology'), ('MA', 'Manufacturing'), ('RE', 'Retail'), ('TE', 'Technology'), ('TR', 'Transportation'), ('OT', 'Other Transportation Type')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='incident',
            name='scenario',
            field=models.BooleanField(default=False, help_text='Is this a real life Incident or a Ficticous Scenario?'),
        ),
        migrations.AddField(
            model_name='incident',
            name='transportation_type_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
