# Generated by Django 2.2.7 on 2019-12-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0011_auto_20191218_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
