# Generated by Django 2.2.7 on 2019-12-19 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0012_incident_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='transportation_type_other',
            new_name='industry_type_other',
        ),
    ]
