# Generated by Django 2.2.7 on 2019-12-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0013_auto_20191218_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
