# Generated by Django 2.2.7 on 2019-12-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0015_auto_20191218_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='bribe_type_other',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='bribed_by_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
