# Generated by Django 3.1.4 on 2020-12-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0020_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/images/'),
        ),
    ]
