# Generated by Django 3.1.4 on 2021-01-05 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0022_incident_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='incident',
            name='documents',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='IncidentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(upload_to='incidents/uploads/')),
                ('incident', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rlcis.incident')),
            ],
        ),
    ]
