# Generated by Django 3.1.4 on 2021-01-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0023_auto_20210104_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='document',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='documents',
        ),
    ]
