# Generated by Django 3.1.4 on 2021-01-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0024_auto_20210105_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentdocument',
            old_name='documents',
            new_name='document',
        ),
    ]
