# Generated by Django 3.1.4 on 2021-01-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0025_auto_20210105_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentdocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
