# Generated by Django 3.1.4 on 2021-02-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0027_remove_incidentdocument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='level',
            field=models.CharField(blank=True, choices=[('FE', 'Federal'), ('PR', 'Provincial'), ('MU', 'Municipal')], max_length=2, null=True),
        ),
    ]
