# Generated by Django 3.1.4 on 2021-03-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0028_auto_20210211_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='level',
            field=models.CharField(blank=True, choices=[('LO', 'Local'), ('ST', 'State/Provincial'), ('NA', 'National')], max_length=2, null=True),
        ),
    ]
