# Generated by Django 3.1.4 on 2021-03-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlcis', '0029_auto_20210302_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='risks',
            field=models.TextField(null=True),
        ),
    ]
