version: "3.8"
services:
  rlcs:
     build: .
     volumes:
       - .:/rlcis
     ports:
       - 8000:8000
     env_file:
       - ./.env.dev
     image: rlcis:rlcis
     container_name: django_container
     command: python manage.py runserver 0.0.0.0:8000
     depends_on:
       - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - .:/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=rlcis
      - POSTGRES_USER=rlcisadm
      - POSTGRES_PASSWORD=12345678
    container_name: postgres_db_container
  
# volumes:
#   postgress_data

