version: "3.8"

services:
  pgdb:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=rlcs
      - POSTGRES_USER=rlcisadm
      - POSTGRES_PASSWORD=12345678
      - PGDATA=/tmp
    container_name: postgres_pgdb
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pgdb
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
  rlcs:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/rlcs
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    image: rlcs:1
    container_name: django_rlcs
    environment: 
      - DEBUG=1
    depends_on:
      - pgdb


volumes:
  postgres_data: