services:
  pgdb:
    image: postgres:12.0-alpine
    container_name: postgres_pgdb
    restart: unless-stopped
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pgdb
    env_file:
      - ./.env.dev
    ports:
      - "5555:80"
    restart: unless-stopped
  rlcs:
    # if building locally, uncomment line 22 and 23 and comment line 24
    # build: .
    # image: rlcs:1
    image: alexandroidii/cst8333-rlcs:1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/rlcs
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    container_name: django_rlcs
    depends_on:
      - pgdb
    restart: unless-stopped

volumes:
  postgres_data: