version: "3.8"
services:
  rlcs:
     build: .
     volumes:
       - .:/rlcs
     ports:
       - 8000:8000
     env_file:
       - ./.env.dev
     image: rlcis:rlcs
     container_name: django_rlcs
     command: python manage.py runserver 0.0.0.0:8000
     depends_on:
       - pgdb
  pgdb:
    image: postgres:12.0-alpine
    volumes:
      - .:/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=docker-rlcs
      - POSTGRES_USER=rlcisadm
      - POSTGRES_PASSWORD=12345678
    container_name: postgres_pgdb
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pgdb
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres_data: