# Generated by Django 3.2 on 2021-04-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BribedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BribeFacilitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BribeInitiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BribeRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BribeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelOfAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('scenario_summary', models.CharField(max_length=200, null=True)),
                ('scenario_details', models.TextField(null=True)),
                ('risks', models.TextField(null=True)),
                ('resolution', models.TextField(null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('region', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('bribe_initiator_other', models.CharField(blank=True, max_length=100, null=True)),
                ('bribe_facilitator_other', models.CharField(blank=True, max_length=100, null=True)),
                ('bribe_recipient_other', models.CharField(blank=True, max_length=100, null=True)),
                ('bribe_type_other', models.CharField(blank=True, max_length=60, null=True)),
                ('industry_type_other', models.CharField(blank=True, max_length=100, null=True)),
                ('first_occurence', models.DateField(blank=True, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text='Has this been reviewed?', null=True)),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('submitted_date', models.DateField(auto_now=True, null=True)),
                ('anonymous', models.BooleanField(default=False, null=True)),
                ('is_training_scenario', models.BooleanField(default=False, help_text='Is this a real life Scenario or a Ficticous Scenario?')),
                ('email', models.EmailField(max_length=254)),
                ('bribe_facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcs.bribefacilitator')),
                ('bribe_initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcs.bribeinitiator')),
                ('bribe_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcs.briberecipient')),
                ('bribe_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcs.bribetype')),
                ('bribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcs.bribedby')),
                ('industry_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcs.industrytype')),
                ('levelOfAuthority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rlcs.levelofauthority')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='scenarios/uploads/')),
                ('scenario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rlcs.scenario')),
            ],
        ),
    ]
