# Generated by Django 3.2 on 2021-04-22 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rlcs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='reviewer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_reviewer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
